services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: Karthik
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  db-data: